BKEngine: bkengine::Serializable Class Reference
bkengine::Serializable Class Reference
Provides a skeleton for basic serialization and deserialization together with a backup and restore mechanism.
#include <Serializable.h>
Public Member Functions
virtual void deserialize (const Json::Value &json)
Uses a JSON object to set member variables.
virtual Json::Value serialize () const
Serializes the object to a JSON object.
void backup ()
Backups the current state of the object.
void restore ()
Restores any backup of the object.
std::string toString () const
Creates a (beautified) string representation of the object.
Detailed Description
Provides a skeleton for basic serialization and deserialization together with a backup and restore mechanism.
Definition at line 17 of file Serializable.h.
Member Function Documentation
backup()
void Serializable::backup ()
Backups the current state of the object.
Through a call to Serializable::serialize the current state of the object is backupped to allow the current state to be restored later on.
Note: This overrides any backups done by Serializable::deserialize!
See also
Serializable::deserialize
Serializable::serialize
Serializable::restore
Definition at line 22 of file Serializable.cpp.
deserialize()
void Serializable::deserialize (const Json::Value & json) virtual
Uses a JSON object to set member variables.
Is used by subclasses to simplify serialization. The default implementation creates a backup of json to allow resetting the object later on.
The recommended way of using this method is following:
void SubSerialize::deserialize(const Json::Value &json)
{
    Serialize::deserialize(json);
    // add your own code here
}
In this way you ensure that the overridden methods will be called anyways.
See also
Serializable::serialize
Serializable::backup
Serializable::restore
Reimplemented in bkengine::Animation, bkengine::Game, bkengine::Element, bkengine::Scene, and bkengine::Texture.
Definition at line 12 of file Serializable.cpp.
Referenced by bkengine::Texture::deserialize(), bkengine::Scene::deserialize(), bkengine::Element::deserialize(), bkengine::Game::deserialize(), bkengine::Animation::deserialize(), and restore().
restore()
void Serializable::restore ()
Restores any backup of the object.
If any backup has been created so far (through calls to Serializable::deserialize or Serializable::backup) it will be restored with calling Serializable::deserialize. Note: This overrides does NOT override the current backup.
See also
Serializable::deserialize
Serializable::serialize
Serializable::restore
Definition at line 27 of file Serializable.cpp.
serialize()
Json::Value Serializable::serialize () const virtual
Serializes the object to a JSON object.
Subclasses can override this method to map its members to a JSON object which allows to save it to a file and restore it later on (given that Serializable::deserialize is overridden as well!).
The default implementation returns any backup done by Serializable::deserialize or Serializable::backup (or an empty object if none of them has been called).
The recommended way of using this method is following:
Json::Value SubSerialize::serialize()
{
    Json::Value json = Serialize::serialize();
    // add your own code here
    return json;
}
This way you ensure that all serialization done by super classes is really done!
See also
Serializable::deserialize
Serializable::backup
Serializable::restore
Reimplemented in bkengine::Animation, bkengine::Game, bkengine::Element, bkengine::Scene, and bkengine::Texture.
Definition at line 17 of file Serializable.cpp.
Referenced by backup(), and toString().
toString()
std::string Serializable::toString () const
Creates a (beautified) string representation of the object.
Returns
A std::string representing the current state of the object.
Definition at line 34 of file Serializable.cpp.
The documentation for this class was generated from the following files:
/home/skaupper/dev/BKEngine/include/bkengine/Serializable.h
/home/skaupper/dev/BKEngine/src/Serializable.cpp