BKEngine: bkengine::Key Class Reference
bkengine::Key Class Reference
Represents a keyboard key.
#include <Keys.h>
Public Member Functions
Key ()
Creates a instance of Key "UNKNOWN".
Key (const std::string &keyString)
Creates a instance of Key keyString.
bool operator== (const Key &key) const
Compares two instances of Key for equality.
bool operator!= (const Key &key) const
Compares two instances of Key for inequality.
operator const std::string () const
Converts the key to a std::string using the stored representation.
std::string toString () const
Returns the string representation of the key.
Detailed Description
Represents a keyboard key.
Definition at line 11 of file Keys.h.
Constructor & Destructor Documentation
Key()
bkengine::Key::Key (const std::string & keyString) inline
Creates a instance of Key keyString.
Valid values for keyString currently contain all uppercase letters, written-out numbers from zero to nine and a whole bunch of other keys. However, you should not need to call this by yourself. Instead use a predefined instance from Keys.
Parameters
[in] keyString A std::string representing a key.
See also
Keys
Definition at line 32 of file Keys.h.
Member Function Documentation
operator!=()
bool Key::operator!= (const Key & key) const
Compares two instances of Key for inequality.
Simply compares the internally stored string representation.
Parameters
[in] key Instance of Key to compare to.
Returns
true if the representations differ false otherwise
Definition at line 149 of file Keys.cpp.
Referenced by bkengine::Button::Button(), and Key().
operator==()
bool Key::operator== (const Key & key) const
Compares two instances of Key for equality.
Simply compares the internally stored string representation.
Parameters
[in] key Instance of Key to compare to.
Returns
true if both representations are equal false otherwise
Definition at line 144 of file Keys.cpp.
Referenced by bkengine::Button::Button(), and Key().
toString()
std::string Key::toString () const
Returns the string representation of the key.
Returns
The key as std::string.
Definition at line 159 of file Keys.cpp.
Referenced by bkengine::Button::Button(), and Key().
The documentation for this class was generated from the following files:
/home/skaupper/repos/BKEngine/include/bkengine/Keys.h
/home/skaupper/repos/BKEngine/src/Keys.cpp