BKEngine: bkengine::Point Struct Reference
bkengine::Point Struct Reference
Represents a point in a two dimensional system.
#include <Misc.h>
Public Member Functions
Point ()
Creates a instance of the point (0/0).
Point (float x, float y)
Creates a instance of the point (x/y).
operator Rect () const
Converts the point into an instance of Rect.
std::string toString () const
Returns a string representation of the point.
SDL_Point toSDLPoint () const
Returns the point represented as SDL_Point.
Public Attributes
float x
float y
Detailed Description
Represents a point in a two dimensional system.
See also
Size
Definition at line 18 of file Misc.h.
Constructor & Destructor Documentation
Point()
bkengine::Point::Point (float x, float y) inline
Creates a instance of the point (x/y).
Parameters
[in] x x coordinate of the point.
[in] y y coordinate of the point.
Definition at line 33 of file Misc.h.
Member Function Documentation
operator Rect()
Point::operator Rect () const
Converts the point into an instance of Rect.
The resulting Rect will be composed like "{ x, y, 0, 0 }".
See also
Rect
Definition at line 10 of file Misc.cpp.
toSDLPoint()
SDL_Point Point::toSDLPoint () const
Returns the point represented as SDL_Point.
Returns
A SDL_Point representation of the point.
Definition at line 21 of file Misc.cpp.
Referenced by Point().
toString()
std::string Point::toString () const
Returns a string representation of the point.
The representation looks like "<Point {x: 1.0; y: 2.0}>" therefore it is not suitable for any kind of calculation.
Returns
A string representation of the point.
Definition at line 15 of file Misc.cpp.
Referenced by bkengine::Color::Color(), Point(), bkengine::Rect::Rect(), and bkengine::Size::Size().
The documentation for this struct was generated from the following files:
/home/skaupper/repos/BKEngine/include/bkengine/Misc.h
/home/skaupper/repos/BKEngine/src/Misc.cpp